config/routes.rb
Rails.application.routes.draw do
  get 'cocktails/show'
    root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show, :create, :new, :destroy] do
    resources :doses, only: [:index, :show, :create, :new, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses , dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence:true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :ingredient_id, uniqueness: { scope: [:cocktail_id] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  def destroy
   @cocktail = Cocktail.find(params[:id])
   @cocktail.destroy
   redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end



end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
   @cocktail = Cocktail.find(params[:cocktail_id])
   @dose = Dose.new(dose_params)
   @dose.cocktail = @cocktail
   @dose.save
   redirect_to cocktail_path(@cocktail)
 end

 def destroy
   @dose = Dose.find(params[:id])
   @dose.destroy
   @cocktail = Cocktail.find(params[:cocktail_id])
   redirect_to cocktail_path(@cocktail)
 end


 private

 def dose_params
  params.require(:dose).permit(:description, :ingredient_id)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/1283219/pexels-photo-1283219.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
  <div class="banner-content">
    <h1>Cocktail Library</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <%= link_to cocktail_path(cocktail) do %>
      <div class="card-wrapper">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
        url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill if cocktail.photo.url %>')">
        <div class="card-description">
          <h2><%= cocktail.name.capitalize %></h2>
          <p>description</p>
        </div>
        <!--  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>
</div>

app/views/cocktails/new.html.erb
<div class="container padding-top-70">


<h1>Create new Cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>

<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

<%= link_to 'Back', cocktails_path %>

</div>

app/views/cocktails/show.html.erb
<div class="container padding-top-70">
  <div class="row">


    <h1><%= @cocktail.name.capitalize %></h1>

    <h2>Doses:</h2>

    <ul>
     <% @doses.each do |dose| %>
     <li>
      <p>
        <b>
          <%=dose.ingredient.name.capitalize %>:</b> <%= dose.description %>
          <%= link_to 'Delete Cocktail dose', cocktail_dose_path(@cocktail, dose), method: :delete %>
        </p>
      </li>
      <%end %>
    </ul>















    <%= link_to 'Delete Cocktail', cocktail_path(@cocktail), method: :delete %>
    <p> <%= link_to 'Add Cocktail doses', new_cocktail_dose_path(@cocktail)  %></p>

    <p> <%= link_to 'Back to Cocktail List', cocktails_path%></p>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container padding-top-70">


<h1>Add cocktail Doses</h1>

<%= simple_form_for([@cocktail, @dose]) do |f| %>

  <div class="form-inputs">
    <%= f.association :ingredient %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', cocktails_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>



<body>
  <%= render 'shared/navbar' %>

  <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="https://static1.squarespace.com/static/52f97bd4e4b08c719fef7e1b/56e327fb1bbee01578e1d85b/56e327fc20c647b40eed0526/1457727489818/Day-10-e.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <%= link_to 'Add cocktail',  new_cocktail_path, class: 'navbar-wagon-item navbar-wagon-link' %>



    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
      <%= image_tag 'steven.jpg', class: "avatar dropdown-toggle", id:"navbar-wagon-menu", data: { toggle: 'dropdown' }%>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>